sudo: true
dist: trusty

env:
  - DOCKER_IMG=tinydnn/tinydnn


jobs:
  include:
    - stage: lints
      env:
        - RUN_LINTS=ON
      script: ./travis_script.sh
    - stage: test
      os:
        - linux
        - osx
      env:
        - BUILD_TESTS=ON
      script: ./travis_script.sh
    - stage: examples
      env:
        - BUILD_EXAMPLES=ON
      script: ./travis_script.sh

cache:
  - docker
