sudo: required
dist: trusty
osx_image: xcode8

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

cache:
  pip: true
  directories:
    - $HOME/.pip-cache/
    # store old benchmarks binary here for comparison
    - $HOME/.benchmarks/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-4.9
      - g++-4.9
      - clang-3.6
      - cmake
      - git
      # Optional dependencies
      - libtbb-dev
      # coveralls dependencies
      - gem
      - lcov
      # caffe-importer dependencies
      - libprotobuf-dev
      - protobuf-compiler

branches:
  only:
    - master
    - feat/xtensor_integration
    - feat/parameters_refactor

env:
  global:
    - USE_TBB=ON
    - BUILD_TESTS=ON
    - BUILD_EXAMPLES=ON
    - BUILD_BENCHMARKS=OFF
    - COVERALLS=ON

  matrix:
    - USE_SSE=OFF USE_AVX=OFF USE_DOUBLE=OFF
    - USE_SSE=ON  USE_AVX=ON USE_DOUBLE=OFF
    - USE_SSE=ON  USE_AVX=ON USE_DOUBLE=ON

matrix:
  exclude: # On OSX g++ is a symlink to clang++ by default
    - os: osx
      compiler: gcc

  include:
    - os: linux
      compiler: gcc
      env: BUILD_BENCHMARKS=ON USE_AVX=ON

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then
       export CC="gcc-4.9";
       export CXX="g++-4.9";
    fi
  - gcc --version
  - g++ --version

install:
  - bash -x .travis/install.sh
  - gem install coveralls-lcov

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++-4.9" ]; then
      lcov --directory . --zerocounters;
      cmake -DUSE_TBB=$USE_TBB
            -DUSE_SSE=$USE_SSE
            -DUSE_AVX=$USE_AVX
            -DUSE_DOUBLE=$USE_DOUBLE
            -DBUILD_TESTS=$BUILD_TESTS
            -DCOVERALLS=$COVERALLS
            -DUSE_ASAN=ON
            -DBUILD_EXAMPLES=$BUILD_EXAMPLES
            -DBUILD_BENCHMARKS=$BUILD_BENCHMARKS .;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "clang++" ]; then
      cmake -DUSE_SSE=$USE_SSE
            -DUSE_AVX=$USE_AVX
            -DBUILD_TESTS=$BUILD_TESTS
            -DBUILD_EXAMPLES=$BUILD_EXAMPLES .;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      cmake -DUSE_TBB=$USE_TBB
            -DUSE_AVX=OFF
            -DBUILD_TESTS=$BUILD_TESTS .;
    fi

script:
  - if [ "$BUILD_BENCHMARKS" == "ON" ]; then
      make tiny_dnn_benchmarks;
      benchmarks/tiny_dnn_benchmarks;

      if [ -f "$HOME/.benchmarks/tiny_dnn_benchmarks" ]; then
        ./benchmark-src/tools/compare_bench.py $HOME/.benchmarks/tiny_dnn_benchmarks benchmarks/tiny_dnn_benchmarks;
      else
        echo "No previous benchmarks binary to compare with, skipping comparison!";
      fi

      cp benchmarks/tiny_dnn_benchmarks $HOME/.benchmarks;
      echo "Saved current benchmarks binary for next build.";

    else
      make -j2;
      test/tiny_dnn_test;
    fi

  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++-4.8" ] && [ "$USE_SSE" == "ON" ] && [ "$USE_AVX" == "ON" ] && [ "$USE_DOUBLE" == "ON" ]; then
      make clang-format-check;
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++-4.9" ]; then
      lcov --directory . --capture --output-file coverage.info;
      lcov --remove coverage.info 'test/*' 'third_party/*' 'cereal/*' '/usr/*' 'tiny_dnn/io/caffe/caffe.pb.*' --output-file coverage.info;
      lcov --list coverage.info;
      coveralls-lcov --source-encoding=ISO-8859-1 coverage.info;
    fi
