init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  home: C:\projects
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    generator : Visual Studio 14 2015
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    generator : Visual Studio 14 2015 Win64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    generator : Visual Studio 15 2017
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    generator : Visual Studio 15 2017 Win64

version: '{branch}-{build}'

branches:
  only:
    - master
    - feat/xtensor_integration

install:
  # Clone submodule
  - git submodule update --init --recursive

# gradient-check test is too slow to execute on debug mode
configuration: Release

before_build:
  - cmd: cd %home%
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "%generator%" -DUSE_SSE=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release ..\tiny-dnn

after_build:
  - cmd: 'cd C:\projects\build\test\Release'
  - cmd: tiny_dnn_test.exe

build_script:
  - msbuild C:\projects\build\tiny_dnn.sln /m

